# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:
#     # password: '{cipher}AQAr9NQIoo9Da3191Z8ivoBog+GP9GL/qSbJllf58X3UXBHYkv14zLn8BRBl9xPzE7Dcc5seAFnlYC79FM3ZeAkut70zHXwddOrPj86t3Q70wFla7XwzMvzeBqUwDGkcKyFJbrvSms/+gWEB8169UNVR/SDEO1se+vxVLlNcwLp2ooPWkw698jRR8lZs/SKcv0XjbAziiR374XsELm0DFN0+/VWu2kKZU7Kw5XaxiGup6fz0KGzYxahP3lLC4dy4wNcknD3b64pDgVZNvNDfGQrBGP35H5/KuQkGJgbM+1oQ3VQmq+qnCSYeDWGsMu1LfimZBM63OBGb3kIlEnBNAr5Y08casp8nkYeyFVzkZ4uCXbWwJdei++iYqbLzQscczw0='
spring:
  datasource:
    url: jdbc:mariadb://mariadb:13306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test1234
token:
  expiration_time: 86400000
  secret: '{cipher}AQB3nvVf6V/LFazXyhQ98Uc+MUPYV+svG+KsaVavUApz8UXv512Wum8tbZKnYggt2PSlSyb15VXjmME94ucGEMvnSxLwXl4bvExJoq1zNOxccaViR3XWCWRuomR+zVjmsUX9GpmzEgGkPgtss/dzdn4nFMvjRjpSEDR8xc9BXiKnz+1s27+cJ6EsAeMggyDKsxsUBlRvkaExP/tDmJNRWsf/SW9n2Etu3PtUsaY29ndDk6/PH2u6dJel8C4FDCrSBrfYG/lge4pQFi8o1xtCtcnAjDXsSEyee0+BEAdJwbliIqzdhuwvE05MeFiI5WsA9YA6wjK1dNsNEgB7McOmk0E90ppa32jSZFyeHe+x181ifBN0aRBgJZRMG6WmGiRm2mDdFd2y90phWe52bo7VxfuM'

gateway:
  ip: 172.18.0.2

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception: 
    order_is_empty: User's order is Empty


logging:
  level:
    com.example.userservice.client: DEBUG